// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/winartodev/apollo-be/core/helper"
	"github.com/winartodev/apollo-be/modules/user/delivery/http"
	"github.com/winartodev/apollo-be/modules/user/domain/service"
	"github.com/winartodev/apollo-be/modules/user/repository"
	"github.com/winartodev/apollo-be/modules/user/usecase"
)

// Injectors from wire.go:

func InitializeUserAPI(database *helper.DatabaseUtil, redis *helper.RedisUtil, jwt *helper.JWT) (*http.UserHandler, error) {
	userRepository, err := repository.NewUserRepository(database)
	if err != nil {
		return nil, err
	}
	userService, err := service.NewUserService(userRepository)
	if err != nil {
		return nil, err
	}
	userUseCase, err := usecase.NewUserUseCase(userService)
	if err != nil {
		return nil, err
	}
	userHandler := http.NewUserHandler(userUseCase)
	return userHandler, nil
}
