// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package country

import (
	"github.com/winartodev/apollo-be/modules/country/delivery/http"
)

// Injectors from wire.go:

func InitializeCountryAPI() (*http.CountryHandler, error) {
	countryHandler := http.NewCountryHandler()
	return countryHandler, nil
}
